In [2]:
import numpy as np

## One dimensional array concepts

In [3]:
#1. Using a NumPy function, how would you create a one-dimensional NumPy array of the numbers from 10 to 100, counting by 10?
np.arange(10, 110, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
#2. Create the same array using a python list
np.array([i for i in range(10, 110, 10)])

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
#3. How would you create a ten-element NumPy array object of all zeros?
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#4. How would you find the data type of the above array
zero_array = np.zeros(10)
zero_array.dtype

dtype('float64')

In [7]:
#5. Recreate the same array but with ones instead
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
#6. Create a 10 element array of random integers
np.random.randint(10,50,2) #first two arguments specify lower and upper bounds. third argument specifies array length

array([36, 15])

In [9]:
#7. Create a normal distribution using numpy

np.random.normal(10, 1, 50) # arguments represent mean, stddev and array size

array([ 8.65565704, 10.52765609,  9.45782683, 10.9141805 ,  8.99664434,
       11.54385352,  9.29457733, 10.91260882, 10.52044306,  8.69749646,
       10.53996129, 11.19360681, 12.75709542, 10.07312119, 10.92506975,
       11.39224874,  9.52265982,  8.15627607, 10.55013001,  9.67286931,
       11.98471888,  9.87654564, 10.94206058, 10.41697761, 11.3649347 ,
       10.8882521 ,  8.91581597, 11.51940252,  7.92980921,  9.28492549,
        9.69853497,  8.01804646,  9.70802897, 10.96292207,  8.27588005,
        7.16490961,  9.89960627,  9.33751539,  9.32782501, 10.01943224,
        9.42180625,  8.71461752, 10.52213915, 11.01992901, 11.06455347,
       10.16295688, 10.89239908,  9.7917526 , 10.55899268, 11.53452102])

In [10]:
#8. What code would create an array of 10 random numbers between zero and one?
np.random.randint(0, 2, 10)

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0])

## Multi-dimensional array concepts

In [11]:
#9. How would you convert a 1 dimensional array to a 2 dimensional array

example_array = np.zeros(12)
example_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
example_array.reshape(4,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
# Create a 3x3 array filled with zeros.

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#11. create a two-dimensional, 3 x 4 array (three arrays of four elements each) with random numbers from 1 to 10

np.random.randint(1, 11, (3,4))

array([[ 3,  9,  2, 10],
       [ 1, 10,  3,  8],
       [ 9, 10,  3,  4]])

In [58]:
# Create a 4x4 array of random integers between 10 and 50. Extract the first two rows and the last two columns.

four_by_four = np.random.randint(10, 50, (4, 4))

four_by_four[0:2, -2:]

array([[25, 48],
       [25, 14]])

In [59]:
# Create a 3x3 matrix of random integers between 5 and 15, and reshape it into a 9x1 array.

a = np.random.randint(5, 15, (3, 3))
a

array([[11,  6,  8],
       [ 8,  9, 10],
       [12, 13, 14]])

In [60]:
a.reshape(9,1)

array([[11],
       [ 6],
       [ 8],
       [ 8],
       [ 9],
       [10],
       [12],
       [13],
       [14]])

In [65]:
y

array([False, False,  True])

In [81]:
# Given a 1D array of size 16, reshape it into a 4x4 2D array. Then, flatten the 2D array back into a 1D array.

arr = np.arange(16)

arr = arr.reshape(4,4)
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
arr = arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
# Create two arrays a = [1, 2, 3] and b = [4, 5, 6]. Stack them vertically and horizontally.

a = np.array([1,2,3])
b = np.array([4,5,6])

vertical_arr = np.vstack((a,b))
vertical_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
horizontal_arr = np.hstack((a,b))
horizontal_arr

array([1, 2, 3, 4, 5, 6])

In [74]:
# Split a 1D array of 12 elements into 3 sub-arrays of 4 elements each.

arr = np.arange(12)

np.split(arr, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [75]:
# the above solution only works if the array length is divisible by the number of splits. if the array length is not evenly divisible by the number of splits, you can use np.array_split(). This function splits the array into the desired number of sub-arrays, but it does not require the array to be evenly divisible. It will distribute the remaining elements as evenly as possible across the sub-arrays.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sub_arrays = np.array_split(arr, 4)

print(sub_arrays)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [13]:
#10. What happens when you rename an array to create a copy and perform changes on the copy

x = example_array
x[0] = 42
x

array([42.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
example_array

array([42.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

ssigning a NumPy array to a new variable simply creates a reference to the original array, not a copy of it. If you need the original array to be unchanged, use

In [ ]:
x = example_array.copy()
x[0] = 54
x

array([54.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
example_array

array([42.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
z_list = [z for z in range(0,5)]
print(z_list)
y_list = [z_list for y in range(0,4)]
print(y_list)
x_list = [y_list for x in range(0,3)]
print(x_list)
x_array = np.array(x_list)

[0, 1, 2, 3, 4]
[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
[[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]], [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]], [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]]


In [20]:
x_array

array([[[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [22]:
x_array.shape # x_array has three 2 dimensional lists of 4 x 5

(3, 4, 5)

In [21]:
x_array.ndim

3

## Indexing and Slicing 2D Arrays

In [24]:
four_by_five = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
#print the first row

four_by_five[0,:]

array([1, 2, 3, 4, 5])

In [28]:
#print the last row
four_by_five[-1,:]

array([16, 17, 18, 19, 20])

In [29]:
# print the first column
four_by_five[:,0]

array([ 1,  6, 11, 16])

In [30]:
# print the third and fourth column
four_by_five[:,3:5]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [32]:
# print the last two columns of the middle two rows

four_by_five[1:3,-2:]

array([[ 9, 10],
       [14, 15]])

In [84]:
# Given a 2D array, set all elements in the second column to zero

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr[:,2] = 0

## Vectorized Operations

In [35]:
x = np.arange(10,110,15)
x

array([ 10,  25,  40,  55,  70,  85, 100])

In [37]:
y = x + 2
y

array([ 12,  27,  42,  57,  72,  87, 102])

In [38]:
print(x > 10)

[False  True  True  True  True  True  True]


In [39]:
x[x > 10]

array([ 25,  40,  55,  70,  85, 100])

In [64]:
# Given two arrays a = [5, 10, 15] and b = [15, 10, 5], check if the elements of a are greater than the elements of b
a = np.array([5, 10, 15])
b = np.array([15, 10, 5])
y = a > b

In [66]:
# Given a 2D array arr, find out which elements are greater than a threshold value of 5.

arr = np.array([[1, 2, 6], [4, 5, 9], [7, 8, 3]])

arr[arr > 5]

array([6, 9, 7, 8])

## Working with files

In [40]:
## Working with stringsg

## Additional Practice Problems

In [41]:
#After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner
#. You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?


# gold states how much gold is under each location in the 7x7 grid of land
# locs states the coordinates of the five locations where you dig

np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

In [42]:
gold

array([[2, 3, 0, 5, 2, 0, 3],
       [8, 8, 0, 7, 1, 5, 3],
       [0, 1, 6, 2, 1, 4, 5],
       [4, 0, 8, 9, 9, 8, 7],
       [4, 2, 7, 0, 7, 2, 1],
       [9, 8, 9, 2, 5, 0, 8],
       [1, 9, 8, 2, 6, 4, 3]])

In [43]:
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

In [44]:
locs

array([[0, 4],
       [2, 2],
       [2, 3],
       [5, 1],
       [6, 3]])

In [48]:
gold_found = [gold[loc[0], loc[1]] for loc in locs]
print(sum(gold_found))

20


In [56]:
# Create an array with 10 equally spaced numbers between 1 and 100
np.arange(1, 101, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])